project_id = "pnxwemmpxldriwaomiey"

[functions.fetch-weather-data]
verify_jwt = false

[functions.generate-neurodiversity-background]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true
